name: clang-format Check

on: 
  push:
    branches:
      - "feature/*"
      - "bugfix/*"
      - "main"
    paths:
      - "Eagle/**"
      - "Sandbox/**"
      - "CMakeList.txt"
      - ".github/workflows/eagle_build.yml"
  pull_request:
    branches:
      - "main"

jobs:
  Formatting-Check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'Eagle'
            exclude: '(Platform/ImGui)'
          - check: 'Sandbox'
            exclude: ''              # Nothing to exclude
    steps:
    - name: Checkout reposistory and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '14'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}